version: "3.8"
services:
  backend:
    build: ./backend
    restart: always
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/data:/app/data

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: "/api"
    restart: always
    expose:
      - "3000"

  nginx:
    image: nginx:1.25
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend