apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: prompty
  namespace: prompty

resources:
  - namespace.yaml
  - configmap.yaml
  - persistent-volume.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - nginx-deployment.yaml
  - ingress.yaml

commonLabels:
  app: prompty
  version: v2

images:
  - name: prompty-backend
    newTag: latest
  - name: prompty-frontend
    newTag: latest 